/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    `maven-publish`
    id("org.springframework.boot") version "3.2.5"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("com.alibaba:druid-spring-boot-starter:1.1.17")
    implementation("com.baomidou:mybatis-plus-boot-starter:3.4.2")
    implementation("org.springframework.boot:spring-boot-starter:2.3.4.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-aop:2.3.4.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-web:2.3.4.RELEASE")
    implementation("com.alibaba:easyexcel:3.0.0-beta3")
    implementation("mysql:mysql-connector-java:8.0.18")
    implementation("com.alibaba:fastjson:1.2.47")
    implementation("org.springframework.boot:spring-boot-starter-mail:2.3.4.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-thymeleaf:2.3.4.RELEASE")
    compileOnly("org.projectlombok:lombok:1.18.32")
    testCompileOnly("org.projectlombok:lombok:1.18.32")

    annotationProcessor("org.projectlombok:lombok:1.18.32")
    annotationProcessor("org.springframework.boot:spring-boot-configuration-processor:2.3.4.RELEASE")

    testAnnotationProcessor("org.projectlombok:lombok:1.18.32")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.3.4.RELEASE")
}

group = "org.sanyuankexie"
version = "0.1.0"
description = "GCTAAttendanceSystem"
java.sourceCompatibility = JavaVersion.VERSION_11

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.getByName<org.springframework.boot.gradle.tasks.bundling.BootJar>("bootJar") {
    this.archiveFileName.set("${archiveBaseName.get()}.${archiveExtension.get()}")
}
